version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: rpg-bdd
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbsql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db-sql:/var/lib/mysql
    networks:
      - bd-rpg

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: rpg-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - bd-rpg

volumes:
  db-sql:

networks:
  bd-rpg: {}
